version: 2

linters:
  disable-all: true
  enable:
    - errcheck # Check for unchecked errors in function calls
    - govet # Official Go static analysis tool to find bugs and potential issues
    - ineffassign # Detect unused assignments
    - staticcheck # Advanced Go linter that detects bugs and performance issues
    - unused # Check for unused constants, variables, functions and types
    - asasalint # Detect pass of []any as any in variadic func(...any)
    - asciicheck # Ensure identifiers only contain ASCII characters
    - bidichk # Detect dangerous unicode character sequences
    - bodyclose # Check whether HTTP response body is closed successfully
    - contextcheck # Check whether the function uses a non-inherited context
    - decorder # Verify consistency in declaration order (constants, variables, types)
    - dogsled # Detect excessive use of blank identifiers in assignments
    - errname # Enforce consistent error variable naming conventions
    - errorlint # Find code that will cause problems with the error wrapping scheme
    - copyloopvar # Check for pointers to enclosing loop variables
    - gocheckcompilerdirectives # Verify compiler directives like //go:generate
    - gochecknoinits # Check that no init functions are present in Go code
    - goconst # Find repeated strings that could be replaced by a constant
    - gocritic # Comprehensive Go source code linter
    - godot # Check if comments end in a period
    - goheader # Check presence and format of copyright headers
    - gomodguard # Control package imports
    - goprintffuncname # Enforce consistent printf-like function naming conventions
    - grouper # Group related constant/variable/import/type declarations
    - importas # Enforce consistent import aliases
    - interfacebloat # Detect interface declarations with too many methods
    - loggercheck # Check key value pairs for common logger libraries
    - makezero # Find slice declarations with non-zero initial length
    - misspell # Find commonly misspelled English words in comments
    - nakedret # Find naked returns in functions larger than specified size
    - nestif # Report deeply nested if statements
    - nilerr # Find code returning nil when err is not nil
    - noctx # Find HTTP requests sent without context.Context
    - nolintlint # Report ill-formed or insufficient nolint directives
    - prealloc # Find slice declarations that could potentially be pre-allocated
    - predeclared # Find shadowing of Go's predeclared identifiers
    - reassign # Check that package variables are not reassigned
    - testableexamples # Check if examples are testable (have an expected output)
    - testpackage # Make sure that separate _test packages are used
    - tparallel # Detect inappropriate usage of t.Parallel() method in tests
    - unconvert # Remove unnecessary type conversions
    - unparam # Report unused function parameters
    - usestdlibvars # Detect the possibility to use variables/constants from stdlib
    - wastedassign # Find wasted assignment statements
    - whitespace # Detect leading and trailing whitespace

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
  govet:
  staticcheck:
    checks: ["all"]
  unused:
    check-exported: false
  unparam:
    check-exported: false
  gocritic:
  prealloc:

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
